package com.nf147.pet.dao;

import com.nf147.pet.entity.Pet;

import java.util.List;

public interface PetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbg.generated
     */
    int insert(Pet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbg.generated
     */
    Pet deleteByPrimaryKey(String eId);


    List<Pet> selectAll();

    int add(List<Pet> list);
}